### ISSUE TITLE
AppMesh iptables Proxy config?

### ISSUE THREAD

**Issue by joshuabaird** [aws/amazon-vpc-cni-plugins#25]
Apologies if this isn't the correct place to ask such a question.  

Given an ECS container instance with an AppMesh-enabled task (an application container and an Envoy proxy sidecar), how can I view the iptables rules created in https://github.com/aws/amazon-vpc-cni-plugins/blob/master/plugins/aws-appmesh/plugin/commands.go?  I'm looking to verify these rules using the `iptables` command. 

I don't see them on the host, or in any of the Docker network namespaces for the application or Envoy containers.  Any tips would be much appreciated!

**Comment by joshuabaird** [comment]
Closing this, because I realized I was looking in the wrong place. 

For anyone else interested in how to verify these iptables rules on a host:

* On your "app-mesh" enabled application container, you should see a network namespace with the same name as the container ID.  You can verify this by running `ip netns`.
* Once you have the namespace, you can query `iptables` by running `ip netns exec $namespaceID iptables -t nat -L`

**Comment by ofiliz** [comment]
Thanks for documenting. Yes, that is correct. All awsvpc tasks have their own dedicated network namespace. AppMesh iptables rules for each task are configured separately for each task inside its network namespace.
