### ISSUE TITLE
Specify UID and GID for vpc-branch-eni plugin

### ISSUE THREAD

**Issue by haikuoliu** [aws/amazon-vpc-cni-plugins#32]
### Summary

Today we can specify UserName for branch vpc-branch-eni plugin, the plugin will do a look up for the user and determine the uid, then change the owner of the tap device to that uid. 

But for our use case we'd like to specify UID and GID directly, can we introduce new config like `UID` and `GID` and set the ownership of tap device accordingly? The implementation is quite straightforward and I am happy to submit a PR for it.

**Comment by ofiliz** [comment]
Fixed by #33
