### ISSUE TITLE
CNI should support containerd on Windows

### ISSUE THREAD

**Issue by backjo** [aws/amazon-vpc-cni-plugins#56]
### Summary

When containers are provisioned through containerd on Windows (instead of docker), the CNI plugin fails
on the ADD operation.

### Description

When containers are started through containerd on Windows, the ADD operation fails due to this logic here -> https://github.com/aws/amazon-vpc-cni-plugins/blob/master/plugins/vpc-shared-eni/network/bridge_windows.go#L361

It seems like a simple fix would be to just assume that the block that has the error is invoked in the case of containerd/cri usage, in which case we can probably assume that it's only being invoked on the infra container.

### Expected Behavior
The CNI should ADD successfully for containers started through containerd. 

### Observed Behavior
The CNI fails the ADD operation for containers started through containerd. 

### Supporting Log Snippets

```
2021-08-26T19:03:55Z [INFO] Executing ADD with netconfig: &{NetConf:{CNIVersion:0.3.1 Name:vpc Type:vpc-shared-eni Capabilities:map[] IPAM:{Type:} DNS:{Names
ervers:[172.20.0.10] Domain: Search:[addon-manager-logging.svc.cluster.local svc.cluster.local cluster.local] Options:[]}} ENIName: ENIMACAddress:0a:df:16:54
:db:51 ENIIPAddress:10.17.42.208/24 VPCCIDRs:[{IP:10.17.32.0 Mask:ffffe000} {IP:10.17.64.0 Mask:ffffe000} {IP:10.17.96.0 Mask:ffffe000}] BridgeType:L3 Bridge
NetNSPath: IPAddress:10.17.42.99/24 GatewayIPAddress:10.17.42.1 InterfaceType:veth TapUserID:0 Kubernetes:{Namespace:addon-manager-logging PodName:fluent-bit
-windows-tb4ds PodInfraContainerID:20fe247f82deb6d6311c0318918999fa40d4b715b61cc97f3c264e6bb1944f79 ServiceCIDR:172.20.0.0/16}} ContainerID:20fe247f82deb6d63
11c0318918999fa40d4b715b61cc97f3c264e6bb1944f79 Netns:504314d1-16b7-47e3-8cc2-b80c1510d1b5 IfName:eth0 Args:K8S_POD_INFRA_CONTAINER_ID=20fe247f82deb6d6311c03
18918999fa40d4b715b61cc97f3c264e6bb1944f79;K8S_POD_UID=fa8bdee8-3c26-4657-8b7e-b76a1fda5601;IgnoreUnknown=1;K8S_POD_NAMESPACE=addon-manager-logging;K8S_POD_N
AME=fluent-bit-windows-tb4ds.
2021-08-26T19:03:55Z [INFO] Running on HNS version: {Major:9 Minor:5}
2021-08-26T19:03:55Z [INFO] Found existing HNS network vpcbr0adf1654db51.
2021-08-26T19:03:55Z [ERROR] Failed to parse netns 504314d1-16b7-47e3-8cc2-b80c1510d1b5 of container 20fe247f82deb6d6311c0318918999fa40d4b715b61cc97f3c264e6b
b1944f79
```

**Comment by rawahars** [comment]
Hi @backjo, I am closing this issue now since the containerd support is available now with the CNI plugin as well as with Amazon EKS. For more information, please visit our documentation [here](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-windows-ami.html#containerd-bootstrap-windows).
