### ISSUE TITLE
EKS node upgrade failed | aws CNI and istio cni

### ISSUE THREAD

**Issue by deepakjeena** [aws/amazon-vpc-cni-plugins#95]
### Summary

EKS node upgrade failing when using istio CNI plugin, 

### Description

EKS is working fine when I am installing aws CNI then istio with istio CNI, both are running fine with eks and if eks autoscale itself new node up successfully, 
But at later stage when i trying to upgrade nodegroup the entire upgrade progress is failing, AWS CNI pod (aws-node) is failing on new upgrade node due to which node upgrade process is failing.

**Comment by ofiliz** [comment]
Hi, did you mean to file this issue in https://github.com/aws/amazon-vpc-cni-k8s?
